### ISSUE TITLE
uploader_login_page.py no longer working

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-ci#10]
When `uploader_login_page.py` calls Auth0 to update the `default_client` client with the new login page, Auth0 returns a response implying success but the actual login page is not updated.

Here is an example response from Auth0 that did not result in the login page being updated. I've trimmed the giant `custom_login_page` and `custom_login_page_preview` values.

```json
{
  "name":"Default App",
  "callbacks":[

  ],
  "tenant":"auth-dev",
  "global":false,
  "allowed_clients":[

  ],
  "allowed_logout_urls":[

  ],
  "custom_login_page_preview":"...ipt>\n    <script src=\"https://cdn.sso.allizom.org/nlx/8596379/js/main.js\"></script>\n  </body>\n</html>\n",
  "sso":true,
  "is_first_party":true,
  "is_token_endpoint_ip_header_trusted":false,
  "description":"test",
  "oidc_conformant":true,
  "client_metadata":{
    "oidc_conformant":"true"
  },
  "logo_uri":"",
  "cross_origin_auth":false,
  "custom_login_page":"...ipt>\n    <script src=\"https://cdn.sso.allizom.org/nlx/bb795c9/js/main.js\"></script>\n  </body>\n</html>\n",
  "allowed_origins":[

  ],
  "client_id":"IxJG9EkWRwW9Zo2a7VoLwndTqrpN7Aln",
  "callback_url_template":false,
  "config_route":null,
  "jwt_configuration":{
    "alg":"HS256",
    "lifetime_in_seconds":36000
  },
  "token_endpoint_auth_method":"client_secret_post",
  "grant_types":[
    "authorization_code",
    "client_credentials",
    "http://auth0.com/oauth/grant-type/mfa-oob",
    "http://auth0.com/oauth/grant-type/mfa-otp",
    "http://auth0.com/oauth/grant-type/mfa-recovery-code",
    "http://auth0.com/oauth/grant-type/password-realm",
    "http://auth0.com/oauth/legacy/grant-type/access_token",
    "http://auth0.com/oauth/legacy/grant-type/ro",
    "http://auth0.com/oauth/legacy/grant-type/ro/jwt-bearer",
    "implicit",
    "password",
    "refresh_token"
  ],
  "web_origins":[

  ],
  "custom_login_page_on":true
}
```

**Comment by gdestuynder** [comment]
this is no longer the valid client id - maybe since the update
please now use `VNGM4quJw3Nhx28j8XKVYmu5LcPMCgAH`

how i found this:
- Go to https://manage-dev.mozilla.auth0.com/docs/api/management/v2#!/Clients/
- Get all clients and show fields for custom login pages
- Scroll through and figure out which ones have a value ;-)

**Comment by gene1wood** [comment]
Cool, thank you. I've changed the `/iam/nlx/lock_client_id` SSM parameter for auth0-custom-lock from `IxJG9EkWRwW9Zo2a7VoLwndTqrpN7Aln` to `VNGM4quJw3Nhx28j8XKVYmu5LcPMCgAH`

**Comment by gene1wood** [comment]
I've deleted the `custom_login_page` and `custom_login_page_preview` payloads from the `IxJG9EkWRwW9Zo2a7VoLwndTqrpN7Aln` client in auth0-dev so we don't encounter it down the road and get confused
